"""
Read parcels from a committed snapshot file instead of the live ArcGIS API.

Production containers can't reach www.ocgis.com (geo-blocked from Hetzner
Helsinki). The snapshot at data/oc-parcels.json.gz is generated by
scripts/snapshot_parcels.py from a dev machine that *can* reach ArcGIS,
then committed to the repo.

Returns None if no snapshot file exists, so the seed gracefully falls
back to live streaming in dev environments.
"""

from __future__ import annotations

import gzip
import json
import logging
from collections.abc import AsyncIterator
from pathlib import Path

log = logging.getLogger(__name__)

SNAPSHOT_PATH = Path("data/oc-parcels.json.gz")


def snapshot_parcels_if_present(limit: int | None = None) -> AsyncIterator[dict] | None:
    """If the snapshot file exists, return an async iterator over its parcels.
    Otherwise return None so callers can fall back to the live source.
    """
    if not SNAPSHOT_PATH.exists():
        return None
    return _iter_snapshot(limit)


async def _iter_snapshot(limit: int | None) -> AsyncIterator[dict]:
    with gzip.open(SNAPSHOT_PATH, "rt", encoding="utf-8") as f:
        parcels = json.load(f)
    log.info("snapshot loaded: %d parcels (limit=%s)", len(parcels), limit)
    for i, p in enumerate(parcels):
        if limit is not None and i >= limit:
            return
        yield p
